//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAvis.WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.CarCategory BilCatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.RentalStation EndStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InsuranceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationsnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.RentalStation StartStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalPrizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.CarCategory BilCat {
            get {
                return this.BilCatField;
            }
            set {
                if ((object.ReferenceEquals(this.BilCatField, value) != true)) {
                    this.BilCatField = value;
                    this.RaisePropertyChanged("BilCat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.RentalStation EndStation {
            get {
                return this.EndStationField;
            }
            set {
                if ((object.ReferenceEquals(this.EndStationField, value) != true)) {
                    this.EndStationField = value;
                    this.RaisePropertyChanged("EndStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Insurance {
            get {
                return this.InsuranceField;
            }
            set {
                if ((this.InsuranceField.Equals(value) != true)) {
                    this.InsuranceField = value;
                    this.RaisePropertyChanged("Insurance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reservationsnummer {
            get {
                return this.ReservationsnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationsnummerField, value) != true)) {
                    this.ReservationsnummerField = value;
                    this.RaisePropertyChanged("Reservationsnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.RentalStation StartStation {
            get {
                return this.StartStationField;
            }
            set {
                if ((object.ReferenceEquals(this.StartStationField, value) != true)) {
                    this.StartStationField = value;
                    this.RaisePropertyChanged("StartStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrize {
            get {
                return this.TotalPrizeField;
            }
            set {
                if ((this.TotalPrizeField.Equals(value) != true)) {
                    this.TotalPrizeField = value;
                    this.RaisePropertyChanged("TotalPrize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarCategory", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class CarCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalStation", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class RentalStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationCode {
            get {
                return this.StationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StationCodeField, value) != true)) {
                    this.StationCodeField = value;
                    this.RaisePropertyChanged("StationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StationId {
            get {
                return this.StationIdField;
            }
            set {
                if ((this.StationIdField.Equals(value) != true)) {
                    this.StationIdField = value;
                    this.RaisePropertyChanged("StationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Terminated = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalAgent", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class RentalAgent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.RentalStation PrimaryLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentId {
            get {
                return this.AgentIdField;
            }
            set {
                if ((this.AgentIdField.Equals(value) != true)) {
                    this.AgentIdField = value;
                    this.RaisePropertyChanged("AgentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashPass {
            get {
                return this.HashPassField;
            }
            set {
                if ((object.ReferenceEquals(this.HashPassField, value) != true)) {
                    this.HashPassField = value;
                    this.RaisePropertyChanged("HashPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.RentalStation PrimaryLocation {
            get {
                return this.PrimaryLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryLocationField, value) != true)) {
                    this.PrimaryLocationField = value;
                    this.RaisePropertyChanged("PrimaryLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/WCF_AVIS")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCAvis.WcfService.CarCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberPlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OdometerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCAvis.WcfService.CarCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberPlate {
            get {
                return this.NumberPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberPlateField, value) != true)) {
                    this.NumberPlateField = value;
                    this.RaisePropertyChanged("NumberPlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Odometer {
            get {
                return this.OdometerField;
            }
            set {
                if ((this.OdometerField.Equals(value) != true)) {
                    this.OdometerField = value;
                    this.RaisePropertyChanged("Odometer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IAVISservice")]
    public interface IAVISservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/SaveResevation", ReplyAction="http://tempuri.org/IAVISservice/SaveResevationResponse")]
        void SaveResevation(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/SaveResevation", ReplyAction="http://tempuri.org/IAVISservice/SaveResevationResponse")]
        System.Threading.Tasks.Task SaveResevationAsync(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/SearchReservation", ReplyAction="http://tempuri.org/IAVISservice/SearchReservationResponse")]
        MVCAvis.WcfService.Reservation SearchReservation(string searchVariable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/SearchReservation", ReplyAction="http://tempuri.org/IAVISservice/SearchReservationResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation> SearchReservationAsync(string searchVariable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Search", ReplyAction="http://tempuri.org/IAVISservice/SearchResponse")]
        MVCAvis.WcfService.Reservation[] Search(MVCAvis.WcfService.Reservation searchVariable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Search", ReplyAction="http://tempuri.org/IAVISservice/SearchResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation[]> SearchAsync(MVCAvis.WcfService.Reservation searchVariable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Update", ReplyAction="http://tempuri.org/IAVISservice/UpdateResponse")]
        void Update(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Update", ReplyAction="http://tempuri.org/IAVISservice/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Delete", ReplyAction="http://tempuri.org/IAVISservice/DeleteResponse")]
        void Delete(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Delete", ReplyAction="http://tempuri.org/IAVISservice/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(MVCAvis.WcfService.Reservation res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/CalcPrice", ReplyAction="http://tempuri.org/IAVISservice/CalcPriceResponse")]
        double CalcPrice(string cat, string dest, System.DateTime dstart, System.DateTime dslut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/CalcPrice", ReplyAction="http://tempuri.org/IAVISservice/CalcPriceResponse")]
        System.Threading.Tasks.Task<double> CalcPriceAsync(string cat, string dest, System.DateTime dstart, System.DateTime dslut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetReservations", ReplyAction="http://tempuri.org/IAVISservice/GetReservationsResponse")]
        MVCAvis.WcfService.Reservation[] GetReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetReservations", ReplyAction="http://tempuri.org/IAVISservice/GetReservationsResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation[]> GetReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetStations", ReplyAction="http://tempuri.org/IAVISservice/GetStationsResponse")]
        MVCAvis.WcfService.RentalStation[] GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetStations", ReplyAction="http://tempuri.org/IAVISservice/GetStationsResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.RentalStation[]> GetStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetCategories", ReplyAction="http://tempuri.org/IAVISservice/GetCategoriesResponse")]
        MVCAvis.WcfService.CarCategory[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/GetCategories", ReplyAction="http://tempuri.org/IAVISservice/GetCategoriesResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.CarCategory[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/MatchStation", ReplyAction="http://tempuri.org/IAVISservice/MatchStationResponse")]
        MVCAvis.WcfService.RentalStation MatchStation(string stationcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/MatchStation", ReplyAction="http://tempuri.org/IAVISservice/MatchStationResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.RentalStation> MatchStationAsync(string stationcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/CreateSalt", ReplyAction="http://tempuri.org/IAVISservice/CreateSaltResponse")]
        string CreateSalt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/CreateSalt", ReplyAction="http://tempuri.org/IAVISservice/CreateSaltResponse")]
        System.Threading.Tasks.Task<string> CreateSaltAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Hasher", ReplyAction="http://tempuri.org/IAVISservice/HasherResponse")]
        string Hasher(string pass, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/Hasher", ReplyAction="http://tempuri.org/IAVISservice/HasherResponse")]
        System.Threading.Tasks.Task<string> HasherAsync(string pass, string salt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/validateAcess", ReplyAction="http://tempuri.org/IAVISservice/validateAcessResponse")]
        int validateAcess(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/validateAcess", ReplyAction="http://tempuri.org/IAVISservice/validateAcessResponse")]
        System.Threading.Tasks.Task<int> validateAcessAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/validateUser", ReplyAction="http://tempuri.org/IAVISservice/validateUserResponse")]
        MVCAvis.WcfService.RentalAgent validateUser(string n, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/validateUser", ReplyAction="http://tempuri.org/IAVISservice/validateUserResponse")]
        System.Threading.Tasks.Task<MVCAvis.WcfService.RentalAgent> validateUserAsync(string n, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/AddUser", ReplyAction="http://tempuri.org/IAVISservice/AddUserResponse")]
        bool AddUser(MVCAvis.WcfService.RentalAgent ren);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/AddUser", ReplyAction="http://tempuri.org/IAVISservice/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(MVCAvis.WcfService.RentalAgent ren);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/AddCar", ReplyAction="http://tempuri.org/IAVISservice/AddCarResponse")]
        bool AddCar(MVCAvis.WcfService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAVISservice/AddCar", ReplyAction="http://tempuri.org/IAVISservice/AddCarResponse")]
        System.Threading.Tasks.Task<bool> AddCarAsync(MVCAvis.WcfService.Car car);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAVISserviceChannel : MVCAvis.WcfService.IAVISservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AVISserviceClient : System.ServiceModel.ClientBase<MVCAvis.WcfService.IAVISservice>, MVCAvis.WcfService.IAVISservice {
        
        public AVISserviceClient() {
        }
        
        public AVISserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AVISserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVISserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVISserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveResevation(MVCAvis.WcfService.Reservation res) {
            base.Channel.SaveResevation(res);
        }
        
        public System.Threading.Tasks.Task SaveResevationAsync(MVCAvis.WcfService.Reservation res) {
            return base.Channel.SaveResevationAsync(res);
        }
        
        public MVCAvis.WcfService.Reservation SearchReservation(string searchVariable) {
            return base.Channel.SearchReservation(searchVariable);
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation> SearchReservationAsync(string searchVariable) {
            return base.Channel.SearchReservationAsync(searchVariable);
        }
        
        public MVCAvis.WcfService.Reservation[] Search(MVCAvis.WcfService.Reservation searchVariable) {
            return base.Channel.Search(searchVariable);
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation[]> SearchAsync(MVCAvis.WcfService.Reservation searchVariable) {
            return base.Channel.SearchAsync(searchVariable);
        }
        
        public void Update(MVCAvis.WcfService.Reservation res) {
            base.Channel.Update(res);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(MVCAvis.WcfService.Reservation res) {
            return base.Channel.UpdateAsync(res);
        }
        
        public void Delete(MVCAvis.WcfService.Reservation res) {
            base.Channel.Delete(res);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(MVCAvis.WcfService.Reservation res) {
            return base.Channel.DeleteAsync(res);
        }
        
        public double CalcPrice(string cat, string dest, System.DateTime dstart, System.DateTime dslut) {
            return base.Channel.CalcPrice(cat, dest, dstart, dslut);
        }
        
        public System.Threading.Tasks.Task<double> CalcPriceAsync(string cat, string dest, System.DateTime dstart, System.DateTime dslut) {
            return base.Channel.CalcPriceAsync(cat, dest, dstart, dslut);
        }
        
        public MVCAvis.WcfService.Reservation[] GetReservations() {
            return base.Channel.GetReservations();
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.Reservation[]> GetReservationsAsync() {
            return base.Channel.GetReservationsAsync();
        }
        
        public MVCAvis.WcfService.RentalStation[] GetStations() {
            return base.Channel.GetStations();
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.RentalStation[]> GetStationsAsync() {
            return base.Channel.GetStationsAsync();
        }
        
        public MVCAvis.WcfService.CarCategory[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.CarCategory[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public MVCAvis.WcfService.RentalStation MatchStation(string stationcode) {
            return base.Channel.MatchStation(stationcode);
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.RentalStation> MatchStationAsync(string stationcode) {
            return base.Channel.MatchStationAsync(stationcode);
        }
        
        public string CreateSalt() {
            return base.Channel.CreateSalt();
        }
        
        public System.Threading.Tasks.Task<string> CreateSaltAsync() {
            return base.Channel.CreateSaltAsync();
        }
        
        public string Hasher(string pass, string salt) {
            return base.Channel.Hasher(pass, salt);
        }
        
        public System.Threading.Tasks.Task<string> HasherAsync(string pass, string salt) {
            return base.Channel.HasherAsync(pass, salt);
        }
        
        public int validateAcess(string user) {
            return base.Channel.validateAcess(user);
        }
        
        public System.Threading.Tasks.Task<int> validateAcessAsync(string user) {
            return base.Channel.validateAcessAsync(user);
        }
        
        public MVCAvis.WcfService.RentalAgent validateUser(string n, string p) {
            return base.Channel.validateUser(n, p);
        }
        
        public System.Threading.Tasks.Task<MVCAvis.WcfService.RentalAgent> validateUserAsync(string n, string p) {
            return base.Channel.validateUserAsync(n, p);
        }
        
        public bool AddUser(MVCAvis.WcfService.RentalAgent ren) {
            return base.Channel.AddUser(ren);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(MVCAvis.WcfService.RentalAgent ren) {
            return base.Channel.AddUserAsync(ren);
        }
        
        public bool AddCar(MVCAvis.WcfService.Car car) {
            return base.Channel.AddCar(car);
        }
        
        public System.Threading.Tasks.Task<bool> AddCarAsync(MVCAvis.WcfService.Car car) {
            return base.Channel.AddCarAsync(car);
        }
    }
}
